hdsleep-dpkg. fix script references.

diff --git a/hdsleep-dpkg/package/usr/bin/hdsleep/hdusage b/hdsleep-dpkg/package/usr/bin/hdsleep/hdusage
--- a/hdsleep-dpkg/package/usr/bin/hdsleep/hdusage
+++ b/hdsleep-dpkg/package/usr/bin/hdsleep/hdusage
@@ -1,4 +1,15 @@
 #!/bin/bash
-usage1=$(iostat -x /dev/sda 5 2 | sed '13!d' | cut -c118)
-usage2=$(iostat -x /dev/sda 5 2 | sed '13!d' | cut -c118)
+
+LOCK_FILE=/tmp/hdsleep.lock
+CONFIG_FILE=/etc/hdsleep/config.cfg
+
+. $CONFIG_FILE
+
+if [ -z $disk ]; then
+        echo "Missing disk configuration. Edit $CONFIG_FILE with the necessary disk value."
+        exit 1
+fi
+
+usage1=$(iostat -x $disk 5 2 | sed '13!d' | cut -c118)
+usage2=$(iostat -x $disk 5 2 | sed '13!d' | cut -c118)
 echo "$(($usage1 + $usage2))"
